name: remote ssh command
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: build docker image and push to registry
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Copy .env.deployment to .env
        run: cp .env.deployment .env
        
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: armensolicy
          password: armen333!

      - name: Extract Git tag
        id: extract_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      
      - name: Build Docker image
        run: docker build -t armensolicy/test-zeep:${{ steps.extract_tag.outputs.TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push armensolicy/test-zeep:${{ steps.extract_tag.outputs.TAG }}
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Extract Git tag
      id: extract_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        
    - name: deploy to prod
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 51.77.202.140
        username: github
        password: testpassword
        port: 22
        script: |
          docker pull armensolicy/test-zeep:${{ steps.extract_tag.outputs.TAG }}
          docker rm -f it_zeepup
          docker run --name it_zeepup --restart always -d -p 8000:80 armensolicy/test-zeep:${{ steps.extract_tag.outputs.TAG }}
