name: Build and Deploy
on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Extract Git tag
      id: extract_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        
    - name: deploy to prod
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_HOST_USER }}
        password: ${{ secrets.SSH_HOST_USER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull "$DOCKER_REGISTRY":${{ steps.extract_tag.outputs.TAG }}
          docker rm -f mobile_zeepup || true
          docker run --name mobile_zeepup --restart always -d -p 8000:80 "$DOCKER_REGISTRY":${{ steps.extract_tag.outputs.TAG }}
