name: Build and Deploy
on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Extract Git tag
      id: extract_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        
    - name: deploy to prod
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_HOST_USER }}
        password: ${{ secrets.SSH_HOST_USER_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull "armensolicy/mobile_zeepup:${{ steps.extract_tag.outputs.TAG }}"
          CONTAINER_NAME="mobile_zeepup"

          if docker ps -a --format '{{.Names}}' | grep -w mobile_zeepup > /dev/null; then
          docker rm -f mobile_zeepup
          fi

          docker run --name mobile_zeepup --restart always -d -p 8080:80 armensolicy/mobile_zeepup:${{ steps.extract_tag.outputs.TAG }}
